### PR TITLE
Move away from VCAP_APP_HOST - it doesn't exist on Diego

### LINKED ISSUE #64: Diego Migration Issue
As Bluemix moves to Diego, one of the changes is that the VCAP_APP_HOST environment variable (which was always set to 0.0.0.0) is no longer set.  I notice we use VCAP_APP_HOST in this project, so this needs to be reviewed.  For more info on the changes: https://github.com/cloudfoundry/diego-design-notes/blob/master/migrating-to-diego.md#cf-specific-environment-variables

### PR DESCRIPTION
**Pull request by lornajane**
These changes allowed the stackoverflow version to work correctly.  Fixes #64

### CODE REVIEW

**Comment by DTAIEB** [comment]
@lornajane I see that you removed the local case from this file. This means that we now always start data pipe locally without https and it will break OAuth which requires https in the callback. Again, this is only breaking when running locally, but I think it's very important that we keep the capability to run and develop locally

**Comment by lornajane** [comment]
I removed the case because it will always fire due to VCAP_APP_HOST being absent, and I thought since it was expected to be present on live, that this was the least harmful way forward.  I'm happy to revisit it but I'm also using the pipe locally and find that I need to make modifications to get it to work on my machine so perhaps this is something we should revisit?

**Comment by DTAIEB** [comment]
@lornajane Yes I think we should revisit. Let's have a quick call to decide the best approach

**Comment by lornajane** [comment]
Agreed with @DTAIEB that we should merge this to get it working on production, then revisit as needed

**Pull request merged**
